#############################################################################
# Makefile for building: MediaStreamer
# Generated by qmake (2.01a) (Qt 4.8.2) on: Mon Sep 24 07:47:32 2012
# Project:  MediaStreamer.pro
# Template: subdirs
# Command: c:\Qt\4.8.2-mingw\bin\qmake.exe -spec c:\Qt\4.8.2-mingw\mkspecs\win32-g++ CONFIG+=release -o Makefile MediaStreamer.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = c:\Qt\4.8.2-mingw\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
SUBTARGETS    =  \
		sub-MSBroadcaster \
		sub-MSAdministrator \
		sub-MSServer \
		sub-Research \
		sub-MSCommon

MSBroadcaster\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) MSBroadcaster\ $(MKDIR) MSBroadcaster\ 
	cd MSBroadcaster\ && $(QMAKE) d:\GitHub\MediaStreamer\MSBroadcaster\MSBroadcaster.pro -spec c:\Qt\4.8.2-mingw\mkspecs\win32-g++ CONFIG+=release -o $(MAKEFILE)
sub-MSBroadcaster-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) MSBroadcaster\ $(MKDIR) MSBroadcaster\ 
	cd MSBroadcaster\ && $(QMAKE) d:\GitHub\MediaStreamer\MSBroadcaster\MSBroadcaster.pro -spec c:\Qt\4.8.2-mingw\mkspecs\win32-g++ CONFIG+=release -o $(MAKEFILE)
sub-MSBroadcaster: MSBroadcaster\$(MAKEFILE) FORCE
	cd MSBroadcaster\ && $(MAKE) -f $(MAKEFILE)
sub-MSBroadcaster-make_default: MSBroadcaster\$(MAKEFILE) FORCE
	cd MSBroadcaster\ && $(MAKE) -f $(MAKEFILE) 
sub-MSBroadcaster-make_first: MSBroadcaster\$(MAKEFILE) FORCE
	cd MSBroadcaster\ && $(MAKE) -f $(MAKEFILE) first
sub-MSBroadcaster-all: MSBroadcaster\$(MAKEFILE) FORCE
	cd MSBroadcaster\ && $(MAKE) -f $(MAKEFILE) all
sub-MSBroadcaster-clean: MSBroadcaster\$(MAKEFILE) FORCE
	cd MSBroadcaster\ && $(MAKE) -f $(MAKEFILE) clean
sub-MSBroadcaster-distclean: MSBroadcaster\$(MAKEFILE) FORCE
	cd MSBroadcaster\ && $(MAKE) -f $(MAKEFILE) distclean
sub-MSBroadcaster-install_subtargets: MSBroadcaster\$(MAKEFILE) FORCE
	cd MSBroadcaster\ && $(MAKE) -f $(MAKEFILE) install
sub-MSBroadcaster-uninstall_subtargets: MSBroadcaster\$(MAKEFILE) FORCE
	cd MSBroadcaster\ && $(MAKE) -f $(MAKEFILE) uninstall
MSAdministrator\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) MSAdministrator\ $(MKDIR) MSAdministrator\ 
	cd MSAdministrator\ && $(QMAKE) d:\GitHub\MediaStreamer\MSAdministrator\MSAdministrator.pro -spec c:\Qt\4.8.2-mingw\mkspecs\win32-g++ CONFIG+=release -o $(MAKEFILE)
sub-MSAdministrator-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) MSAdministrator\ $(MKDIR) MSAdministrator\ 
	cd MSAdministrator\ && $(QMAKE) d:\GitHub\MediaStreamer\MSAdministrator\MSAdministrator.pro -spec c:\Qt\4.8.2-mingw\mkspecs\win32-g++ CONFIG+=release -o $(MAKEFILE)
sub-MSAdministrator: MSAdministrator\$(MAKEFILE) FORCE
	cd MSAdministrator\ && $(MAKE) -f $(MAKEFILE)
sub-MSAdministrator-make_default: MSAdministrator\$(MAKEFILE) FORCE
	cd MSAdministrator\ && $(MAKE) -f $(MAKEFILE) 
sub-MSAdministrator-make_first: MSAdministrator\$(MAKEFILE) FORCE
	cd MSAdministrator\ && $(MAKE) -f $(MAKEFILE) first
sub-MSAdministrator-all: MSAdministrator\$(MAKEFILE) FORCE
	cd MSAdministrator\ && $(MAKE) -f $(MAKEFILE) all
sub-MSAdministrator-clean: MSAdministrator\$(MAKEFILE) FORCE
	cd MSAdministrator\ && $(MAKE) -f $(MAKEFILE) clean
sub-MSAdministrator-distclean: MSAdministrator\$(MAKEFILE) FORCE
	cd MSAdministrator\ && $(MAKE) -f $(MAKEFILE) distclean
sub-MSAdministrator-install_subtargets: MSAdministrator\$(MAKEFILE) FORCE
	cd MSAdministrator\ && $(MAKE) -f $(MAKEFILE) install
sub-MSAdministrator-uninstall_subtargets: MSAdministrator\$(MAKEFILE) FORCE
	cd MSAdministrator\ && $(MAKE) -f $(MAKEFILE) uninstall
MSServer\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) MSServer\ $(MKDIR) MSServer\ 
	cd MSServer\ && $(QMAKE) d:\GitHub\MediaStreamer\MSServer\MSServer.pro -spec c:\Qt\4.8.2-mingw\mkspecs\win32-g++ CONFIG+=release -o $(MAKEFILE)
sub-MSServer-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) MSServer\ $(MKDIR) MSServer\ 
	cd MSServer\ && $(QMAKE) d:\GitHub\MediaStreamer\MSServer\MSServer.pro -spec c:\Qt\4.8.2-mingw\mkspecs\win32-g++ CONFIG+=release -o $(MAKEFILE)
sub-MSServer: MSServer\$(MAKEFILE) FORCE
	cd MSServer\ && $(MAKE) -f $(MAKEFILE)
sub-MSServer-make_default: MSServer\$(MAKEFILE) FORCE
	cd MSServer\ && $(MAKE) -f $(MAKEFILE) 
sub-MSServer-make_first: MSServer\$(MAKEFILE) FORCE
	cd MSServer\ && $(MAKE) -f $(MAKEFILE) first
sub-MSServer-all: MSServer\$(MAKEFILE) FORCE
	cd MSServer\ && $(MAKE) -f $(MAKEFILE) all
sub-MSServer-clean: MSServer\$(MAKEFILE) FORCE
	cd MSServer\ && $(MAKE) -f $(MAKEFILE) clean
sub-MSServer-distclean: MSServer\$(MAKEFILE) FORCE
	cd MSServer\ && $(MAKE) -f $(MAKEFILE) distclean
sub-MSServer-install_subtargets: MSServer\$(MAKEFILE) FORCE
	cd MSServer\ && $(MAKE) -f $(MAKEFILE) install
sub-MSServer-uninstall_subtargets: MSServer\$(MAKEFILE) FORCE
	cd MSServer\ && $(MAKE) -f $(MAKEFILE) uninstall
Research\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) Research\ $(MKDIR) Research\ 
	cd Research\ && $(QMAKE) d:\GitHub\MediaStreamer\Research\Research.pro -spec c:\Qt\4.8.2-mingw\mkspecs\win32-g++ CONFIG+=release -o $(MAKEFILE)
sub-Research-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) Research\ $(MKDIR) Research\ 
	cd Research\ && $(QMAKE) d:\GitHub\MediaStreamer\Research\Research.pro -spec c:\Qt\4.8.2-mingw\mkspecs\win32-g++ CONFIG+=release -o $(MAKEFILE)
sub-Research: Research\$(MAKEFILE) FORCE
	cd Research\ && $(MAKE) -f $(MAKEFILE)
sub-Research-make_default: Research\$(MAKEFILE) FORCE
	cd Research\ && $(MAKE) -f $(MAKEFILE) 
sub-Research-make_first: Research\$(MAKEFILE) FORCE
	cd Research\ && $(MAKE) -f $(MAKEFILE) first
sub-Research-all: Research\$(MAKEFILE) FORCE
	cd Research\ && $(MAKE) -f $(MAKEFILE) all
sub-Research-clean: Research\$(MAKEFILE) FORCE
	cd Research\ && $(MAKE) -f $(MAKEFILE) clean
sub-Research-distclean: Research\$(MAKEFILE) FORCE
	cd Research\ && $(MAKE) -f $(MAKEFILE) distclean
sub-Research-install_subtargets: Research\$(MAKEFILE) FORCE
	cd Research\ && $(MAKE) -f $(MAKEFILE) install
sub-Research-uninstall_subtargets: Research\$(MAKEFILE) FORCE
	cd Research\ && $(MAKE) -f $(MAKEFILE) uninstall
MSCommon\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) MSCommon\ $(MKDIR) MSCommon\ 
	cd MSCommon\ && $(QMAKE) d:\GitHub\MediaStreamer\MSCommon\MSCommon.pro -spec c:\Qt\4.8.2-mingw\mkspecs\win32-g++ CONFIG+=release -o $(MAKEFILE)
sub-MSCommon-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) MSCommon\ $(MKDIR) MSCommon\ 
	cd MSCommon\ && $(QMAKE) d:\GitHub\MediaStreamer\MSCommon\MSCommon.pro -spec c:\Qt\4.8.2-mingw\mkspecs\win32-g++ CONFIG+=release -o $(MAKEFILE)
sub-MSCommon: MSCommon\$(MAKEFILE) FORCE
	cd MSCommon\ && $(MAKE) -f $(MAKEFILE)
sub-MSCommon-make_default: MSCommon\$(MAKEFILE) FORCE
	cd MSCommon\ && $(MAKE) -f $(MAKEFILE) 
sub-MSCommon-make_first: MSCommon\$(MAKEFILE) FORCE
	cd MSCommon\ && $(MAKE) -f $(MAKEFILE) first
sub-MSCommon-all: MSCommon\$(MAKEFILE) FORCE
	cd MSCommon\ && $(MAKE) -f $(MAKEFILE) all
sub-MSCommon-clean: MSCommon\$(MAKEFILE) FORCE
	cd MSCommon\ && $(MAKE) -f $(MAKEFILE) clean
sub-MSCommon-distclean: MSCommon\$(MAKEFILE) FORCE
	cd MSCommon\ && $(MAKE) -f $(MAKEFILE) distclean
sub-MSCommon-install_subtargets: MSCommon\$(MAKEFILE) FORCE
	cd MSCommon\ && $(MAKE) -f $(MAKEFILE) install
sub-MSCommon-uninstall_subtargets: MSCommon\$(MAKEFILE) FORCE
	cd MSCommon\ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: MediaStreamer.pro  c:/Qt/4.8.2-mingw/mkspecs/win32-g++/qmake.conf c:/Qt/4.8.2-mingw/mkspecs/qconfig.pri \
		c:/Qt/4.8.2-mingw/mkspecs/modules/qt_webkit_version.pri \
		c:/Qt/4.8.2-mingw/mkspecs/features/qt_functions.prf \
		c:/Qt/4.8.2-mingw/mkspecs/features/qt_config.prf \
		c:/Qt/4.8.2-mingw/mkspecs/features/exclusive_builds.prf \
		c:/Qt/4.8.2-mingw/mkspecs/features/default_pre.prf \
		c:/Qt/4.8.2-mingw/mkspecs/features/win32/default_pre.prf \
		c:/Qt/4.8.2-mingw/mkspecs/features/release.prf \
		c:/Qt/4.8.2-mingw/mkspecs/features/debug_and_release.prf \
		c:/Qt/4.8.2-mingw/mkspecs/features/default_post.prf \
		c:/Qt/4.8.2-mingw/mkspecs/features/win32/default_post.prf \
		c:/Qt/4.8.2-mingw/mkspecs/features/win32/rtti.prf \
		c:/Qt/4.8.2-mingw/mkspecs/features/win32/exceptions.prf \
		c:/Qt/4.8.2-mingw/mkspecs/features/win32/stl.prf \
		c:/Qt/4.8.2-mingw/mkspecs/features/shared.prf \
		c:/Qt/4.8.2-mingw/mkspecs/features/warn_on.prf \
		c:/Qt/4.8.2-mingw/mkspecs/features/qt.prf \
		c:/Qt/4.8.2-mingw/mkspecs/features/win32/thread.prf \
		c:/Qt/4.8.2-mingw/mkspecs/features/moc.prf \
		c:/Qt/4.8.2-mingw/mkspecs/features/win32/windows.prf \
		c:/Qt/4.8.2-mingw/mkspecs/features/resources.prf \
		c:/Qt/4.8.2-mingw/mkspecs/features/uic.prf \
		c:/Qt/4.8.2-mingw/mkspecs/features/yacc.prf \
		c:/Qt/4.8.2-mingw/mkspecs/features/lex.prf \
		c:/Qt/4.8.2-mingw/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec c:\Qt\4.8.2-mingw\mkspecs\win32-g++ CONFIG+=release -o Makefile MediaStreamer.pro
c:\Qt\4.8.2-mingw\mkspecs\qconfig.pri:
c:\Qt\4.8.2-mingw\mkspecs\modules\qt_webkit_version.pri:
c:\Qt\4.8.2-mingw\mkspecs\features\qt_functions.prf:
c:\Qt\4.8.2-mingw\mkspecs\features\qt_config.prf:
c:\Qt\4.8.2-mingw\mkspecs\features\exclusive_builds.prf:
c:\Qt\4.8.2-mingw\mkspecs\features\default_pre.prf:
c:\Qt\4.8.2-mingw\mkspecs\features\win32\default_pre.prf:
c:\Qt\4.8.2-mingw\mkspecs\features\release.prf:
c:\Qt\4.8.2-mingw\mkspecs\features\debug_and_release.prf:
c:\Qt\4.8.2-mingw\mkspecs\features\default_post.prf:
c:\Qt\4.8.2-mingw\mkspecs\features\win32\default_post.prf:
c:\Qt\4.8.2-mingw\mkspecs\features\win32\rtti.prf:
c:\Qt\4.8.2-mingw\mkspecs\features\win32\exceptions.prf:
c:\Qt\4.8.2-mingw\mkspecs\features\win32\stl.prf:
c:\Qt\4.8.2-mingw\mkspecs\features\shared.prf:
c:\Qt\4.8.2-mingw\mkspecs\features\warn_on.prf:
c:\Qt\4.8.2-mingw\mkspecs\features\qt.prf:
c:\Qt\4.8.2-mingw\mkspecs\features\win32\thread.prf:
c:\Qt\4.8.2-mingw\mkspecs\features\moc.prf:
c:\Qt\4.8.2-mingw\mkspecs\features\win32\windows.prf:
c:\Qt\4.8.2-mingw\mkspecs\features\resources.prf:
c:\Qt\4.8.2-mingw\mkspecs\features\uic.prf:
c:\Qt\4.8.2-mingw\mkspecs\features\yacc.prf:
c:\Qt\4.8.2-mingw\mkspecs\features\lex.prf:
c:\Qt\4.8.2-mingw\mkspecs\features\include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec c:\Qt\4.8.2-mingw\mkspecs\win32-g++ CONFIG+=release -o Makefile MediaStreamer.pro

qmake_all: sub-MSBroadcaster-qmake_all sub-MSAdministrator-qmake_all sub-MSServer-qmake_all sub-Research-qmake_all sub-MSCommon-qmake_all FORCE

make_default: sub-MSBroadcaster-make_default sub-MSAdministrator-make_default sub-MSServer-make_default sub-Research-make_default sub-MSCommon-make_default FORCE
make_first: sub-MSBroadcaster-make_first sub-MSAdministrator-make_first sub-MSServer-make_first sub-Research-make_first sub-MSCommon-make_first FORCE
all: sub-MSBroadcaster-all sub-MSAdministrator-all sub-MSServer-all sub-Research-all sub-MSCommon-all FORCE
clean: sub-MSBroadcaster-clean sub-MSAdministrator-clean sub-MSServer-clean sub-Research-clean sub-MSCommon-clean FORCE
distclean: sub-MSBroadcaster-distclean sub-MSAdministrator-distclean sub-MSServer-distclean sub-Research-distclean sub-MSCommon-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-MSBroadcaster-install_subtargets sub-MSAdministrator-install_subtargets sub-MSServer-install_subtargets sub-Research-install_subtargets sub-MSCommon-install_subtargets FORCE
uninstall_subtargets: sub-MSBroadcaster-uninstall_subtargets sub-MSAdministrator-uninstall_subtargets sub-MSServer-uninstall_subtargets sub-Research-uninstall_subtargets sub-MSCommon-uninstall_subtargets FORCE

sub-MSBroadcaster-sub_Debug: MSBroadcaster\$(MAKEFILE)
	cd MSBroadcaster\ && $(MAKE) -f $(MAKEFILE) debug
sub-MSAdministrator-sub_Debug: MSAdministrator\$(MAKEFILE)
	cd MSAdministrator\ && $(MAKE) -f $(MAKEFILE) debug
sub-MSServer-sub_Debug: MSServer\$(MAKEFILE)
	cd MSServer\ && $(MAKE) -f $(MAKEFILE) debug
sub-Research-sub_Debug: Research\$(MAKEFILE)
	cd Research\ && $(MAKE) -f $(MAKEFILE) debug
sub-MSCommon-sub_Debug: MSCommon\$(MAKEFILE)
	cd MSCommon\ && $(MAKE) -f $(MAKEFILE) debug
debug: sub-MSBroadcaster-sub_Debug sub-MSAdministrator-sub_Debug sub-MSServer-sub_Debug sub-Research-sub_Debug sub-MSCommon-sub_Debug

sub-MSBroadcaster-sub_Release: MSBroadcaster\$(MAKEFILE)
	cd MSBroadcaster\ && $(MAKE) -f $(MAKEFILE) release
sub-MSAdministrator-sub_Release: MSAdministrator\$(MAKEFILE)
	cd MSAdministrator\ && $(MAKE) -f $(MAKEFILE) release
sub-MSServer-sub_Release: MSServer\$(MAKEFILE)
	cd MSServer\ && $(MAKE) -f $(MAKEFILE) release
sub-Research-sub_Release: Research\$(MAKEFILE)
	cd Research\ && $(MAKE) -f $(MAKEFILE) release
sub-MSCommon-sub_Release: MSCommon\$(MAKEFILE)
	cd MSCommon\ && $(MAKE) -f $(MAKEFILE) release
release: sub-MSBroadcaster-sub_Release sub-MSAdministrator-sub_Release sub-MSServer-sub_Release sub-Research-sub_Release sub-MSCommon-sub_Release

sub-MSBroadcaster-check: MSBroadcaster\$(MAKEFILE)
	cd MSBroadcaster\ && $(MAKE) -f $(MAKEFILE) check
sub-MSAdministrator-check: MSAdministrator\$(MAKEFILE)
	cd MSAdministrator\ && $(MAKE) -f $(MAKEFILE) check
sub-MSServer-check: MSServer\$(MAKEFILE)
	cd MSServer\ && $(MAKE) -f $(MAKEFILE) check
sub-Research-check: Research\$(MAKEFILE)
	cd Research\ && $(MAKE) -f $(MAKEFILE) check
sub-MSCommon-check: MSCommon\$(MAKEFILE)
	cd MSCommon\ && $(MAKE) -f $(MAKEFILE) check
check: sub-MSBroadcaster-check sub-MSAdministrator-check sub-MSServer-check sub-Research-check sub-MSCommon-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

