#ifndef MSCOMMON_GLOBAL_H
#define MSCOMMON_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MSCOMMON_LIBRARY)
#  define MSCOMMONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MSCOMMONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MSCOMMON_GLOBAL_H
